### ISSUE TITLE
Login with username (instead of email)

### ISSUE THREAD

**Issue by nextgen-networks** [flionet89/Nextcloud-roundcube#1]
Hello @flionet89,
installed the plugin - unfortunately it does not work with my NC20 installation because i use usernames for login and not email addresses.
To fix this there seems to be a PR in progress already in LeonardoRM's repo (see: https://github.com/LeonardoRM/owncloud-roundcube/pull/8)
Did you tried to integrate this in your fork already?

Thanks for your great effort to bring this to NC!

**Comment by flionet89** [comment]
Hello. Updated the plugin! Now you can use the plugin without having an email as a login. But e-mail must be registered in the user settings.
New version 10.0.3.
