### ISSUE TITLE
settings can not be saved with Nextcloud 20 - error 405

### ISSUE THREAD

**Issue by nextgen-networks** [flionet89/Nextcloud-roundcube#3]
I get an error 405 when trying to save/modify settings.
<html>
<body>

Date | Type | IP | Code | Message | R | Agent | Size | Source
-- | -- | -- | -- | -- | -- | -- | -- | --
2021-05-15 11:46:56 | Error | MYipADDRESS | 405 | POST /index.php/settings/admin/additional HTTP/2.0 |   |   | 0 | nginx SSL/TLS access

</body>
</html>

This happens on Apache as well as nginx.
NC is 20.0.1

In general plugin is working out of the box when passing the roundcube folder via proxy settings to a installed roundcube instance and username = email-address.
But changes on config could not be made.

**Comment by flionet89** [comment]
Hello. I have modified the plugin. I do not quite understand what kind of configuration change we are talking about. Download the latest version of the plugin. If the problem persists, please attach detailed screenshots of the error.

**Comment by nextgen-networks** [comment]
Hi @flionet89,

the error occured when setting up options in Admin / Additional Settings in "RoundCube" Section see:
![image](https://user-images.githubusercontent.com/21206978/119125395-03370280-ba32-11eb-9d03-6a318d1d93d4.png)
After saving any change in those settings I got an ngingx 405 error.

BUT! ... after upgrading to NC21 the problem disappeared today ;-)
Therefore this seems to be an special limitation that could occur on NC20 only.

I'll close this issue - maybe you can update the docs with an information about this limitation.
