### ISSUE TITLE
Cannot get accurate cookies...

### ISSUE THREAD

**Issue by ThongSong7** [flionet89/Nextcloud-roundcube#4]
NextCloud 20 / php7.2-fpm / apache2.4
Cannot get the plugin to work to load, in the console of FF89.0 I see that the cookies for roundcube are expired because they seem to be from 1970 or 1981, but never when I access the page.... could this be the reasons?

https://azerty.com/index.php/apps/roundcube/

RC installed on the same machine....  is this an issue?

hosted roundcube at https://azerty.com/roundcube/ - I set the Default RC installation path to /roundcube/ ?  Cannot get this working.  
Some talk over on the owncloud-roundcube about cookies and the backend not getting cookies?  Related?

**Comment by flionet89** [comment]
Hello. The plugin is adapted for NextCloud 21 and higher.   I recommend upgrading to version 21.

**Comment by ThongSong7** [comment]
@flionet89 
On the NextCloud apps page for this project it is noted as requirements
https://apps.nextcloud.com/apps/nextcloud_roundcube

NextCloud >= 20
Roundcube Webmail >= 1.4
curl

This should be changed to reflect what is on Github and to avoid future confusion. :-)
