### ISSUE TITLE
Unable to login into roundcube. There are login errors. Relogin to ownCloud. Relogin to ownCloud.

### ISSUE THREAD

**Issue by Igortorrente** [flionet89/Nextcloud-roundcube#9]
I was investigating this issue, and this is my conclusion.

When the user login into the account, and therefore providing userID and the password, the function postLogin(lib/AuthHelper.php:46) is called and stores several pieces of information like email, password, server URL, and Roundcube address. 

But this doesn't always happens, like when we don't have to login because Nextcloud is using a cookie to authenticate us. But the app relies on the user providing these pieces of information in the login, and when it doesn't occur it fails and emits the message of the title of this issue.

The biggest problem is that we don't have a way to store the password securely because the autologin relies on the password to be in plaintext(As far as I know).

I was trying to fix the issue myself, but the lack of knowledge of the Nextcloud Framework prevents me from doing it.

**Comment by Igortorrente** [comment]
Apparently, the Rainloop uses the same approach as the Nextcloud mail, which is store the password in the session cookie (https://github.com/pierre-alain-b/rainloop-nextcloud/issues/87#issuecomment-631799829, https://github.com/pierre-alain-b/rainloop-nextcloud/issues/87#issuecomment-444903119, https://github.com/nextcloud/mail/pull/28))

**Comment by dcrobertson01** [comment]
I am still getting this. Is the fix in the released version?

**Comment by Igortorrente** [comment]
No. I have a downstream version of this app that maybe worth a [look](https://github.com/Igortorrente/Nextcloud-roundcube)
